# Generated by Django 4.2.5 on 2023-11-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='companies',
            field=models.ManyToManyField(blank=True, to='mainapp.companies'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.ManyToManyField(blank=True, to='mainapp.education'),
        ),
        migrations.AlterField(
            model_name='person',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='mainapp.experiences'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interests',
            field=models.ManyToManyField(blank=True, to='mainapp.interests'),
        ),
        migrations.AlterField(
            model_name='person',
            name='languages',
            field=models.ManyToManyField(blank=True, to='mainapp.languages'),
        ),
    ]
