# Generated by Django 4.2.5 on 2024-01-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='skill',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
