# Generated by Django 4.2.5 on 2024-01-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_languages_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='experiences',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='experiences',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
