# Generated by Django 4.2.5 on 2024-01-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_experiences_description_experiences_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='projects',
            field=models.ManyToManyField(blank=True, to='mainapp.project'),
        ),
    ]
