# Generated by Django 4.2.5 on 2024-01-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_project_person_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='project_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
