# Generated by Django 4.2.5 on 2024-01-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_person_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='mainapp.skills'),
        ),
    ]
