# Generated by Django 4.2.5 on 2024-02-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_skills_person_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
